-- Add description column to personas table for landing page display
-- This is a short, user-friendly description generated by Groq during persona creation

ALTER TABLE personas 
ADD COLUMN description TEXT;

-- Add comment to document the purpose
COMMENT ON COLUMN personas.description IS 'Short, user-friendly description of the persona displayed on landing page (2-3 sentences, generated by Groq)';

